import { ProductsTypes } from "../types/types";

export const products: ProductsTypes[] = [
  {
    id: 15,
    name: "Benachin for the Whole Compound",
    price: 140000,
    category: "Food",
    icon: "utensils",
    image: "/products/jollof.jpg",
  },
  {
    id: 13,
    name: "Go to the US Just for Selfies",
    price: 70000000,
    category: "Funny",
    icon: "camera",
    image: "/products/selfies-usa.jpg",
  },
  {
    id: 14,
    name: "Hire Professional Attaya Makers",
    price: 70000,
    category: "Leisure",
    icon: "coffee",
    image: "/products/ataya-man.jpg",
  },
  {
    id: 9,
    name: "Diamond Ring",
    price: 140000000,
    category: "Luxury",
    icon: "gem",
    image: "/products/dianond-ring-1.jpg",
  },
  {
    id: 12,
    name: "Buy the Biggest Goat for Tobaski",
    price: 7000000,
    category: "Tradition",
    icon: "gift",
    image: "/products/goatjpg.jpg",
  },
  {
    id: 5,
    name: "Supercar Collection",
    price: 350000000,
    category: "Transport",
    icon: "car",
    image: "/products/supercar-collection.jpg",
  },
  {
    id: 8,
    name: "Art Collection",
    price: 560000000,
    category: "Luxury",
    icon: "palette",
    image: "/products/african-art.jpg",
  },
  {
    id: 7,
    name: "Tech Startup",
    price: 700000000,
    category: "Business",
    icon: "laptop",
    image: "/products/african-tech-startup.jpg",
  },
  {
    id: 11,
    name: "Build a Church in Your Village",
    price: 1050000000,
    category: "Kindness",
    icon: "church",
    image: "/products/church.jpg",
  },
  {
    id: 2,
    name: "Luxury Yacht",
    price: 1050000000,
    category: "Transport",
    icon: "ship",
    image: "/products/luxury-yatch.jpeg",
  },
  {
    id: 17,
    name: "Sponsor 10 Kids’ School Fees",
    price: 1200000,
    category: "Kindness",
    icon: "graduation-cap",
    image: "/products/schoolkids.jpg",
  },
  {
    id: 10,
    name: "Build a Mosque",
    price: 1400000000,
    category: "Kindness",
    icon: "building-2",
    image: "/products/mosque.jpg",
  },
  {
    id: 4,
    name: "Mansion",
    price: 1750000000,
    category: "Real Estate",
    icon: "castle",
    image: "/products/modern-Mansion.jpg",
  },
  {
    id: 1,
    name: "Private Island",
    price: 3500000000,
    category: "Real Estate",
    icon: "tree-palm",
    image: "/products/luxury-private-island.jpg",
  },
  {
    id: 3,
    name: "Private Jet",
    price: 4550000000,
    category: "Transport",
    icon: "plane",
    image: "/products/private-jet.jpg",
  },
  {
    id: 6,
    name: "Football Club",
    price: 10500000000,
    category: "Business",
    icon: "trophy",
    image: "/products/football-club.jpg",
  },
  {
    id: 18,
    name: "Surprise Mama with a House",
    price: 500000000,
    category: "Kindness",
    icon: "home",
    image: "/products/mama-house.jpg",
  },
  {
    id: 19,
    name: "Buy one Bitcoin",
    price: 10771320,
    category: "Investment",
    icon: "bitcoin",
    image: "/products/bitcoin.png",
  },
];